version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/react-front
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: hooks/reload_nginx.sh
      timeout: 180
      runas: ubuntu
