// 액션 타입 생성
// 전체 아티스트 불러오기
const GET_ARTISTS = 'artists/GET_ARTISTS';
const GET_ARTISTS_SUCCESS = 'artists/GET_ARTISTS_SUCCESS';
const GET_ARTISTS_ERROR = 'artists/GET_ARTISTS_ERROR';
// 아티스트 데이터 불러오기
const GET_ARTIST = 'artists/GET_ARTIST';
const GET_ARTIST_SUCCESS = 'artists/GET_ARTIST_SUCCESS';
const GET_ARTIST_ERROR = 'artists/GET_ARTIST_ERROR';
// 아티스트 멤버 불러오기
const GET_ARTIST_MEMBERS = 'artists/GET_ARTIST_MEMBERS';
const GET_ARTIST_MEMBERS_SUCCESS = 'artists/GET_ARTIST_MEMBERS_SUCCESS';
const GET_ARTIST_MEMBERS_ERROR = 'artists/GET_ARTIST_MEMBERS_ERROR';
// 전체 소속사 불러오기
const GET_AGENCY = 'artists/GET_AGENCY';
const GET_AGENCY_SUCCESS = 'artists/GET_AGENCY_SUCCESS';
const GET_AGENCY_ERROR = 'artists/GET_AGENCY_ERROR';
// 소속사 매니저 불러오기
const GET_AGENCY_MANAGERS = 'artist/GET_AGENCY_MANAGER';
const GET_AGENCY_MANAGERS_SUCCESS = 'artist/GET_AGENCY_MANAGER_SUCCESS';
const GET_AGENCY_MANAGERS_ERROR = 'artist/GET_AGENCY_MANAGER_ERROR';
// 취소시 아티스트 데이터 정보 지우기
export const INITIAL_ARTIST = 'artists/INITIAL_ARTIST';
// 소속사 아티스트 검색
const GET_SEARCH_ARTISTS = 'artists/GET_SEARCH_ARTIST';
const GET_SEARCH_ARTISTS_SUCCESS = 'artists/GET_SEARCH_ARTIST_SUCCESS';
const GET_SEARCH_ARTISTS_ERROR = 'artists/GET_SEARCH_ARTIST_ERROR';